### ISSUE TITLE
Yaquina Figures Assignment

### ISSUE THREAD

**Issue by Creutzx** [Creutzx/Upper_Yaquina_Figures#1]
Just writing this to see if you're able to view this.

I'm working through the looping part of the code right now, and will talk to you once it's done.

**Comment by kbrannan** [comment]
Git it

**Comment by kbrannan** [comment]
Yep, I got it and respond via GitHub

**Comment by kbrannan** [comment]
thread mosed to https://github.com/Creutzx/Upper_Yaquina_Figures/issues/2#issue-284986707
