### ISSUE TITLE
Push to github repository

### ISSUE THREAD

**Issue by kbrannan** [Creutzx/Upper_Yaquina_Figures#2]
Let's keep using GitHub for discussing this repository and avoid using other means, such as Outlook.

As related to your last question, check to see if you see yor code in your github repository

Also, type command in Git Bash "git status" let me know what you see.

you can paste a schreen capture to the issue message box directly (see your image below)
![image](https://user-images.githubusercontent.com/7131670/34422679-ac04ed66-ebcb-11e7-8cc6-3d50cedf5867.png)

**Comment by Creutzx** [comment]
Sounds good, I can see my code in the GitHub repository.

![status](https://user-images.githubusercontent.com/32490475/34422958-d09ca6e4-ebcd-11e7-98e1-5fd08d10e676.JPG)

**Comment by kbrannan** [comment]
I can't see the code on github (https://github.com/Creutzx/Upper_Yaquina_Figures)
![pic](https://user-images.githubusercontent.com/7131670/34423186-3725c7a0-ebcf-11e7-87d9-8f73cb5a81bb.png)

Based on the image of your git bash, I think you still need to commit the changes for the py file. 
Use these commands:
git commit -m 'first version of the py file'
git push

Then look at https://github.com/Creutzx/Upper_Yaquina_Figures
respond to this comment when you're done

**Comment by Creutzx** [comment]
I executed both of those commands successfully.

I think the issue may be that I created a branch from the master, and pushed into that branch. (The master branch doesn't have anything in it, but if you switch branches from the master to Fig_Gen, you should be able to see it.)

**Comment by kbrannan** [comment]
Great!
I see the code in the branch.
