### ISSUE TITLE
File Structure for Mapping Script

### ISSUE THREAD

**Issue by Creutzx** [Creutzx/Upper_Yaquina_Figures#4]
I'm getting an error on line 38 that I haven't been able to figure out: (the error is: IndexError: list index out of range). Another thing: printing the names of layers (line 33) yields a list consisting of "or_state_boundary" repeated about 25 times.

I think the root of this problem is that I'm unsure about what types of files, and the structure of those files that I should be working with in those scripts. Also, what should the .mxd file look like? In most of the sample scripts, online help, etc., practitioners generally use shapefiles within a geodatabase, but I recall you cautioning against that specific approach.

**Comment by kbrannan** [comment]
When refering to a problem in code, please send a link to the line in the in the file on GitHub like this:
https://github.com/Creutzx/Upper_Yaquina_Figures/blob/06a1632a980552d3c52cf7668f503eec21c7c3bc/Python/Mapping_Example.py#L3

You can do this by viewing the file on GitHub and then right clicking the line number, then creating a new issue using the link to the file. Then we are sure we are looking at the some file and version. Try that.

**Comment by Creutzx** [comment]
https://github.com/Creutzx/Upper_Yaquina_Figures/blob/057180a0da259a0d82696b15419a52f88373dc2f/Upper_Yaquina_Figures_for_TMDL.py#L38

Sure thing, this is the line where I get the error. And below is what it looks like in the PyCharm window.

![line 38 error](https://user-images.githubusercontent.com/32490475/34538586-cace7680-f081-11e7-9e97-8e9516bda514.JPG)

But I think the crux of my problem is the last part of the issue I posted. I think I'm at a point where I understand the Python coding well enough to generate a series of generic maps, but I don't have a good handle on organizing the files--types, locations, structure--to make the 4-way interaction between GitHub, PyCharm, local repository, and map files work.

**Comment by kbrannan** [comment]
I think I fixed the error you were getting. 
Check out the changes and comments I made in the file
https://github.com/Creutzx/Upper_Yaquina_Figures/blob/942b4cf3f9a32bb1ab92d8bea910deabf60773f4/Upper_Yaquina_Figures_for_TMDL.py#L31

**Comment by kbrannan** [comment]
Did the code suggestion in the last comment address this issue? If so, please close this issue,
