### ISSUE TITLE
Changing the remote repository

### ISSUE THREAD

**Issue by Creutzx** [Creutzx/Upper_Yaquina_Figures#5]
I'm able to set the URL for a new file's remote repository, but am having trouble changing the existing repository for the file I'm working on.

This is the issue I spoke with you about yesterday--whenever I do a commit for this file, it goes to the repository you set up a few months ago.

This is what I've tried:
![change_url](https://user-images.githubusercontent.com/32490475/34623784-86b06364-f207-11e7-8e67-a29dd1ee891f.JPG)

**Comment by kbrannan** [comment]
I think what we did on your machine addressed this issue, so I am closing it
