### ISSUE TITLE
Question about wild card object

### ISSUE THREAD

**Issue by Creutzx** [Creutzx/Upper_Yaquina_Figures#6]
I'm trying to figure out what this object is for:

https://github.com/Creutzx/Upper_Yaquina_Figures/blob/942b4cf3f9a32bb1ab92d8bea910deabf60773f4/Upper_Yaquina_Figures_for_TMDL.py#L10

It's referenced as a wild card later in the script here:

https://github.com/Creutzx/Upper_Yaquina_Figures/blob/942b4cf3f9a32bb1ab92d8bea910deabf60773f4/Upper_Yaquina_Figures_for_TMDL.py#L47

**Comment by kbrannan** [comment]
The chr_lyr_name_sel  variable refers to the name of the watershed boundary in the data frame of the map doc ('HUC 10') that you want to use in the image of the watershed location in the state image you will make. The commands that are commented out below can do this, but are a mess. Let me clean them I will post a updated version on the repository

**Comment by Creutzx** [comment]
Thanks! I figured out the issue I was having with this.

**Comment by kbrannan** [comment]
great
