### ISSUE TITLE
.png output file question

### ISSUE THREAD

**Issue by Creutzx** [Creutzx/Upper_Yaquina_Figures#7]
I've been trying to troubleshoot the error I'm getting for this line of code:

https://github.com/Creutzx/Upper_Yaquina_Figures/blob/ce918ab808f80201f8f8b26ac058284e0f8dd393/Upper_Yaquina_Figures_for_TMDL.py#L58

I've tried a bunch of different things, but I think that there's an issue with this object:

https://github.com/Creutzx/Upper_Yaquina_Figures/blob/ce918ab808f80201f8f8b26ac058284e0f8dd393/Upper_Yaquina_Figures_for_TMDL.py#L9

I'm unclear about what the above line of code does. I thought it directed Python to create the Up_Yaq.png file, but is Python looking for something rather than generating something? Here is the error message.

![exporttopng](https://user-images.githubusercontent.com/32490475/34737738-d4bd1422-f52b-11e7-8d67-6ba4ebd5e228.JPG)

Thank You!

**Comment by kbrannan** [comment]
The path for the png file is in correct. The 'TMDL_WR' is a sub folder of the 'TMDL'
Change to
chr_png_map_new = r'\\DEQHQ1\TMDL\TMDL_WR\MidCoast\GIS\Figures\Upper_Yaquina_Maps\Up_Yaq.png'

**Comment by Creutzx** [comment]
Thanks!
